### ISSUE TITLE
Set up the news feed

### ISSUE THREAD

**Issue by edward-delossantos** [CSCI-40500-77100-Spring-2021/project-15#6]
### To-do:
- [] Design news feed page
- [] Allow users to post and comment
- [] Store data in Firebase
